name: Build Docker Image

on:
  push:
  pull_request:

jobs:
  build:
    permissions:
      id-token: write
      attestations: write
      packages: write
    strategy:
      matrix:
        include:
          - image: ubuntu-24.04
            arch: amd64
          - image: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.image }}
    steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata for sub-image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/ci-temp
        flavor: suffix=.arch.${{ matrix.arch }}
        tags: |
          type=raw,value=run.${{ github.run_id }}
    - uses: docker/build-push-action@v6
      with:
        push: ${{ github.event_name != 'pull_request' }}
        provenance: mode=max
        sbom: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - uses: actions/upload-artifact@v4
      with:
        name: image-${{ matrix.runs-on }}
        path: ./image.tar
  merge:
    runs-on: ubuntu-24.04
    needs: build
    if: github.event_name != 'pull_request'
    steps:
    - uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository }}
        tags:
          type=ref,event=branch
