name: Build Docker Image

on:
  push:
  pull_request:

jobs:
  build:
    permissions:
      id-token: write
      attestations: write
      packages: write
    strategy:
      matrix:
        include:
          - image: ubuntu-24.04
            arch: amd64
          - image: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.image }}
    steps:
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata for sub-image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/ci-temp
        flavor: suffix=.arch.${{ matrix.arch }}
        tags: |
          type=raw,value=run.${{ github.run_id }}
    - uses: docker/build-push-action@v6
      id: push
      with:
        push: ${{ github.event_name != 'pull_request' }}
        provenance: mode=max
        sbom: true
        labels: ${{ steps.meta.outputs.labels }}
        annotations: ${{ steps.meta.outputs.annotations }}
        outputs: type=image,name=ghcr.io/${{ github.repository }},push-by-digest=true,name-canonical=true
    - name: Export digest
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.push.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"
    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ matrix.arch }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1
    - uses: actions/attest-build-provenance@v2
      with:
        subject-name: ghcr.io/${{ github.repository }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: ${{ github.event_name != 'pull_request' }}
  merge:
    runs-on: ubuntu-24.04
    needs: build
    if: github.event_name != 'pull_request'
    steps:
    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: ${{ runner.temp }}/digests
        pattern: digests-*
        merge-multiple: true
    - uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags:
          type=ref,event=branch
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create manifest list and push
      working-directory: ${{ runner.temp }}/digests
      shell: python
      run: |
        import subprocess
        import os
        import json

        metadata = json.loads(os.environ['DOCKER_METADATA_OUTPUT_JSON'])

        subprocess.run([
          "docker", "buildx", "imagetools", "create",
          "--progress", "rawjson",
          *sum([["-t", tag] for tag in metadata['tags']], []),
          # *sum([["--annotation", annotation] for annotation in metadata['annotations']], []),
          *sum([["ghcr.io/${{ github.repository }}@sha256:" + digest] for digest in os.listdir()], []),
        ])
    # - uses: actions/attest-build-provenance@v2
    #   with:
    #     subject-name: ghcr.io/${{ github.repository }}
    #     subject-digest: 
