on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        runs-on:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        provenance: mode=max
        sbom: true
        outputs: type=oci,dest=./image.tar
    - uses: actions/upload-artifact@v4
      with:
        name: image-${{ matrix.runs-on }}
        path: ./image.tar
  merge:
    runs-on: ubuntu-24.04
    needs: build
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: image-ubuntu-24.04
        path: ./image-x64.tar
    - uses: actions/download-artifact@v4
      with:
        name: image-ubuntu-24.04-arm
        path: ./image-arm64.tar
    - run: find .
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository }}
        tags:
          type=ref,event=branch
