name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: pgpassword
        ports:
        - 5432:5432
    env:
      DATABASE_URL: postgres://postgres:pgpassword@localhost:5432/postgres
    steps:
    - uses: actions/checkout@v4
    - working-directory: ${{ runner.temp }}
      run: |
        wget https://github.com/mozilla/sccache/releases/download/v0.9.1/sccache-v0.9.1-x86_64-unknown-linux-musl.tar.gz{,.sha256}
        sha256sum -c - <<< "$(cat sccache-v0.9.1-x86_64-unknown-linux-musl.tar.gz.sha256) sccache-v0.9.1-x86_64-unknown-linux-musl.tar.gz"
        tar xzf sccache-v0.9.1-x86_64-unknown-linux-musl.tar.gz
        mv sccache-v0.9.1-x86_64-unknown-linux-musl/sccache ./
        echo "RUSTC_WRAPPER=$PWD/sccache" >> $GITHUB_ENV
    - run: cargo install sqlx-cli --no-default-features --features postgres --debug
    - run: sqlx migrate run
    - run: cargo build
    - run: cargo run &
    - run: killall sagisawa
    - run: sqlx migrate revert
    - run: sqlx migrate run
    - name: Verify Current SQL is Up to Date
      run: |
        docker run --rm -v /app:$(pwd) -e DATABASE_URL=$DATABASE_URL postgres:17 bash -c "cd /app && ./update-current-schema.sh"
        git diff --exit-code
